const ACTIONS = {
  // api
  GET_CUSTOMERS: 'GET_CUSTOMERS',
  RECEIVE_CUSTOMERS: 'RECEIVE_CUSTOMERS',
  ERROR_CUSTOMER: 'ERROR_CUSTOMER',
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  ADD_CLOCAL: 'ADD_CLOCAL',
  DELETE_CUSTOMER: 'DELETE_CLOCAL',
  DELETE_CLOCAL: 'DELETE_CLOCAL',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  UPDATE_CLOCAL: 'UPDATE_CLOCAL',
  // utils
  CURRENT_CUSTOMER: 'CURRENT_CUSTOMER',
  // products
  ADD_CPRODUCT: 'ADD_CPRODUCT',
  ADD_CPLOCAL: 'ADD_CPLOCAL',
  UPDATE_CPRODUCT: 'UPDATE_CPRODUCT',
  UPDATE_CPLOCAL: 'UPDATE_CPLOCAL',
  DELETE_CPRODUCT: 'DELETE_CPRODUCT',
  DELETE_CPLOCAL: 'DELETE_CPLOCAL'
};

export default ACTIONS;