const ACTIONS = {
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  ADD_LOCAL: 'ADD_LOCAL',
  GET_CUSTOMERS: 'GET_CUSTOMERS',
  RECEIVE_CUSTOMERS: 'RECEIVE_CUSTOMERS',
  ERROR_CUSTOMERS: 'ERROR_CUSTOMERS',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER',
  DELETE_LOCAL: 'DELETE_LOCAL',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  UPDATE_LOCAL: 'UPDATE_LOCAL',
  SEARCH_CUSTOMERS: 'SEARCH_CUSTOMERS',
  ADD_NEW_PRODUCT: 'ADD_NEW_PRODUCT',
  ADD_LOCAL_PRODUCT: 'ADD_LOCAL_PRODUCT',
  UPDATE_ENTRY_PRODUCT: 'UPDATE_ENTRY_PRODUCT',
  UPDATE_LOCAL_PRODUCT: 'UPDATE_LOCAL_PRODUCT',
  DELETE_ENTRY_PRODUCT: 'DELET_ENTRY_PRODUCT',
  DELETE_LOCAL_PRODUCT: 'DELET_LOCAL_PRODUCT'
}

export default ACTIONS
