const ACTIONS = {
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  ADD_LOCAL: 'ADD_LOCAL',
  GET_CUSTOMERS: 'GET_CUSTOMERS',
  RECEIVE_CUSTOMERS: 'RECEIVE_CUSTOMERS',
  ERROR_CUSTOMERS: 'ERROR_CUSTOMERS'
}

export default ACTIONS