const ACTIONS = {
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  PRODUCTION_BATCHES: 'PRODUCTION_BATCHES',
  ADD_ORDER: 'ADD_ORDER',
  DELETE_ORDER: 'DELETE_ORDER',
  SHIFT_ORDER: 'SHIFT_ORDER',
  UNSHIFT_ORDER: 'UNSHIFT_ORDER'
};

export default ACTIONS;