const ACTIONS = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
  ERROR_PRODUCTS: 'ERROR_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_LOCAL: 'ADD_LOCAL',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  DELETE_LOCAL: 'DELETE_LOCAL',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_LOCAL: 'UPDATE_LOCAL',
  SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
  SORT_PRODUCTS: 'SORT_PRODUCTS',
}

export default ACTIONS
