const ACTIONS = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
  ERROR_PRODUCTS: 'ERROR_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
  SORT_PRODUCTS: 'SORT_PRODUCTS'
}

export default ACTIONS
