const ACTIONS = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
  ERROR_PRODUCT: 'ERROR_PRODUCT',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_LOCAL: 'ADD_LOCAL',
  DELETE_PRODUCT: 'DELETE_LOCAL',
  DELETE_LOCAL: 'DELETE_LOCAL',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_LOCAL: 'UPDATE_LOCAL'
};

export default ACTIONS;
